name: Generate and Deploy RSS

on:
  schedule:
    - cron: "0 8,16 * * *"  # 毎日8時と16時に実行
  workflow_dispatch:  # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: チェックアウト
        uses: actions/checkout@v3

      - name: Python セットアップ
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 依存ライブラリのインストール
        run: |
          pip install -r requirements.txt
          playwright install

      - name: RSS 生成スクリプト実行
        run: python main.py

      - name: GitHub Pages へデプロイ
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

